### ISSUE TITLE
IPC::Open3() produces System Error [29]: 'Illegal seek'

### ISSUE THREAD

**Issue by domibay-hugo** [bodo-hugo-barwich/Process#10]
Under "_Perl_" `5.10` the `IPC::Open3()` Function produces a System Error which is taken for a failed Launch although the Sub Process was successfully created:
```
$ perl -v|grep -i built
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
```
```
$ strace -f -o strace_perl-sbprc-qt_2020-09-30-5.log perl -MProcess::SubProcess -e 'print "starting ...\n"; my ($out, $err, $ext) = Process::SubProcess::runSubProcess(("command" => "./quiet_script.pl", "debug" => 1)); print "done.\n"; print "STDOUT:\n$$out\nSTDERR:\n$$err\nEXIT: $ext\n"; '
starting ...
done.
STDOUT:
Process::SubProcess::Run - go ...
Process::SubProcess::Launch - go ...
Sub Process './quiet_script.pl': Launching ...
cmd: './quiet_script.pl'
cmd pfg '0'
sys err 0 (0): ''
cmd pid 1: '28066'
sys err 1 (29): 'Illegal seek'
'Process::SubProcess::runSubProcess' : Signal to 'Process::SubProcess::freeResources'

STDERR:
ERROR: Sub Process './quiet_script.pl': Launch failed with System Error [29]
Message: 'Illegal seek'
Sub Process './quiet_script.pl': Process Launch failed!

EXIT: 29
```
`sys err 0` is read just befor the launch of open3()
and the `cmd pid 1` and `sys err 1` are read just after the launch.

The `strace` shows that both Processes have exit cleanly although an error was notified:
The Sub Process actually was created correctly
```
$ cat strace_perl-sbprc-qt_2020-09-30-5.log|grep -i clone
28048 clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f70a688a9d0) = 28066
$ cat strace_perl-sbprc-qt_2020-09-30-5.log|grep -i exit
28048 exit_group(0)                     = ?
28048 +++ exited with 0 +++
28066 exit_group(0)                     = ?
28066 +++ exited with 0 +++
```
it seems that the "_Perl_" Implementation of `open3()` has produced this error

**Comment by domibay-hugo** [comment]
#14 This change can resolve this issue.
The Automated Tests did succeed, too. So this change will not affect the normal library functionality or operativity.

**Comment by bodo-hugo-barwich** [comment]
I cannot actively support `perl 5.10` because I don't have means to test any development reliably.
So I will accept the Pull Requests as far as the Automated Tests are satisfied.
