### ISSUE TITLE
Makefile.PL or Build.PL is missing

### ISSUE THREAD

**Issue by eserte** [bodo-hugo-barwich/Process#37]
The CPAN distribution is missing a Makefile.PL or Build.PL file and thus cannot be build automatically using CPAN.pm.

See http://matrix.cpantesters.org/?dist=Process-SubProcess+2.1.1 → all test reports are currently UNKNOWN, there are no PASS reports.

**Comment by bodo-hugo-barwich** [comment]
thank you for pointing this out.

Actually I was studying your reports and was wondering over the test results from version `2.1.0` which gave the error:
```plain
------------------------------
PROGRAM OUTPUT
------------------------------

Output from '/usr/bin/make -j2 -j2':

make: *** No targets specified and no makefile found.  Stop.
```

And I was wondering if the pre-build `Makefile` would obstaculise the testing.

I, myself, noticed this today when trying to install the package from CPAN for automation purposes. It gave the error when installing it with `cpanm`:
```plain
--> Working on Process::SubProcess
Fetching http://www.cpan.org/authors/id/B/BO/BODOLFO/Process-SubProcess-2.1.1.tar.gz ... OK
! The distribution doesn't have a proper Makefile.PL/Build.PL See /home/runner/.cpanm/work/1691230564.5248/build.log for details.
Configuring Process-SubProcess-v2.1.1 ... N/A`
```

**Comment by bodo-hugo-barwich** [comment]
I see that the CPAN-Test Scenarios are starting to run now.

But I also notice at:
[Process-SubProcess-2.1.3 5.36.0 FreeBSD](http://www.cpantesters.org/cpan/report/34c7af52-3497-11ee-bed3-d02d6e8775ea)
That required and in `cpanfile` declared dependencies are not installed.
```
Can't locate Getopt/Long/Descriptive.pm in @INC (you may need to install the Getopt::Long::Descriptive module) (@INC contains: /usr/home/cpansand/.cpan/build/2023080600/Process-SubProcess-2.1.3-2/blib/lib /usr/home/cpansand/.cpan/build/2023080600/Process-SubProcess-2.1.3-2/blib/arch /usr/local/lib/perl5/site_perl/mach/5.32 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/mach /usr/local/lib/perl5/5.32 .) at /usr/home/cpansand/.cpan/build/2023080600/Process-SubProcess-2.1.3-2/t/../bin/run_subprocess.pl line 15.
BEGIN failed--compilation aborted at /usr/home/cpansand/.cpan/build/2023080600/Process-SubProcess-2.1.3-2/t/../bin/run_subprocess.pl line 15.
```

**Comment by eserte** [comment]
> I see that the CPAN-Test Scenarios are starting to run now.
> 
> But I also notice at: [...] That required and in `cpanfile` declared dependencies are not installed.
> 
[...]

The dependencies are installed. But within your test suite things are probably called with the wrong perl. See the response in the cpantesters-discuss mailing list I just wrote.

**Comment by eserte** [comment]
It seems that the original issue is resolved.
